name = "profanity-api-demo"
compatibility_date =  "2024-04-16"

[vars]
VECTOR_URL = "https://fast-deer-83754-us1-vector.upstash.io"
VECTOR_TOKEN = "ABMFMGZhc3QtZGVlci04Mzc1NC11czFhZG1pblpHUmtNak5sTmpjdE9UWmpOQzAwTURJeUxUZ3lPVFl0TXpNek9UUmhNREZqTVRRMw=="